version = 0.1
[default.deploy.parameters]
stack_name = "secret-santa-api"
resolve_s3 = true
s3_prefix = "secret-santa-api"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
